---

name: Test

on: 
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: Clansty/build-aur-action@main
        with:
          repo-name: nvidia-open-beta-dkms
      
      - name: check
        run: |
          ls;
          ls nvidia-open-beta-dkms;
          ls nvidia-open-beta-dkms/pkg;
          mkdir packages;
          mv nvidia-open-beta-dkms/*.pkg.tar.xz packages;


        
      - name: Upload Raspberry Images
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: packages/
