---

name: Test

on: 
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      volumes:
        - /proc:/proc
      options: --privileged

    steps:
      - name: Build
        id: build
        uses: Clansty/build-aur-action@main
        with:
          repo-name: yay
      
      - name: check
        run: |
        ls;


        
      #- name: Upload Raspberry Images
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: linux-lqx
      #    path: packages/
