---

name: Test

on: 
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build
        uses: Clansty/build-aur-action@main
        with:
          repo-name: microsoft-edge-stable-bin
      
      - name: check
        run: |
          ls;
          ls microsoft-edge-stable-bin;
          ls microsoft-edge-stable-bin/pkg;
          mkdir packages;
          mv microsoft-edge-stable-bin/*.pkg.tar.xz packages;


        
      - name: Upload Raspberry Images
        uses: actions/upload-artifact@v2
        with:
          name: Packages
          path: packages/
